name: IANT
favicon: null
layout_spectrum: 0.3861161367967725
typography_spectrum: 0.5347430682741106
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.270163603592664
  lightness: 0.07530284230597317
  saturation: 0.7716294021811336
  rhythmicContrast: 0.3600454207044095
purpose: []
